services:
  name_bot:
    build:
      dockerfile: ./Dockerfile
    restart: unless-stopped
    container_name: name_bot
    ports:
      - "8000:8000"
    volumes:
      - .:/data
    command:
      - "python"
      - "main.py"
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock

  name_pg:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - name_pg_data:/var/lib/postgresql/data

volumes:
  name_pg_data:
